export const mockJobs = [
  {
    id: 1,
    title: "Senior React Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120,000 - $160,000",
    description: "We are looking for an experienced React developer to join our team.",
    status: "active",
    applicants: 24,
    featured: true,
  },
  {
    id: 2,
    title: "UX Designer",
    company: "DesignStudio",
    location: "New York, NY",
    type: "Full-time",
    salary: "$90,000 - $130,000",
    description: "Create beautiful user experiences for our products.",
    status: "active",
    applicants: 18,
    featured: false,
  },
  {
    id: 3,
    title: "Product Manager",
    company: "StartupXYZ",
    location: "Remote",
    type: "Full-time",
    salary: "$100,000 - $140,000",
    description: "Lead product strategy and development.",
    status: "active",
    applicants: 12,
    featured: true,
  },
]

export const mockApplications = [
  {
    id: 1,
    candidateName: "John Doe",
    email: "john@example.com",
    phone: "+1-555-123-4567",
    jobTitle: "Senior React Developer",
    appliedDate: "2024-01-15",
    status: "pending",
    rating: 4.5,
  },
  {
    id: 2,
    candidateName: "Jane Smith",
    email: "jane@example.com",
    phone: "+1-555-234-5678",
    jobTitle: "UX Designer",
    appliedDate: "2024-01-14",
    status: "reviewing",
    rating: 4.8,
  },
  {
    id: 3,
    candidateName: "Mike Johnson",
    email: "mike@example.com",
    phone: "+1-555-345-6789",
    jobTitle: "Product Manager",
    appliedDate: "2024-01-13",
    status: "rejected",
    rating: 3.2,
  },
]

export const mockUsers = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    type: "Job Seeker",
    joinDate: "2024-01-01",
    status: "active",
  },
  {
    id: 2,
    name: "Bob Wilson",
    email: "bob@example.com",
    type: "Employer",
    joinDate: "2024-01-05",
    status: "active",
  },
  {
    id: 3,
    name: "Carol Davis",
    email: "carol@example.com",
    type: "Recruiter",
    joinDate: "2024-01-10",
    status: "inactive",
  },
]
